//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoo.Relaxant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int WorkingMinutes {
            get {
                return ((int)(this["WorkingMinutes"]));
            }
            set {
                this["WorkingMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string AdminPassword {
            get {
                return ((string)(this["AdminPassword"]));
            }
            set {
                this["AdminPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free")]
        public global::Hoo.Relaxant.RestrictionLevels Resctriction4Configuration {
            get {
                return ((global::Hoo.Relaxant.RestrictionLevels)(this["Resctriction4Configuration"]));
            }
            set {
                this["Resctriction4Configuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free")]
        public global::Hoo.Relaxant.RestrictionLevels Resctriction4TerminateBreaking {
            get {
                return ((global::Hoo.Relaxant.RestrictionLevels)(this["Resctriction4TerminateBreaking"]));
            }
            set {
                this["Resctriction4TerminateBreaking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DelayMinutes {
            get {
                return ((int)(this["DelayMinutes"]));
            }
            set {
                this["DelayMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShutdownMonitor {
            get {
                return ((bool)(this["ShutdownMonitor"]));
            }
            set {
                this["ShutdownMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BreakingMinutes {
            get {
                return ((int)(this["BreakingMinutes"]));
            }
            set {
                this["BreakingMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free")]
        public global::Hoo.Relaxant.RestrictionLevels Resctriction4Quit {
            get {
                return ((global::Hoo.Relaxant.RestrictionLevels)(this["Resctriction4Quit"]));
            }
            set {
                this["Resctriction4Quit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MusicFile {
            get {
                return ((string)(this["MusicFile"]));
            }
            set {
                this["MusicFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sound4CompletingBreak {
            get {
                return ((string)(this["Sound4CompletingBreak"]));
            }
            set {
                this["Sound4CompletingBreak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo Language {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MaxWorkingMinutes {
            get {
                return ((int)(this["MaxWorkingMinutes"]));
            }
            set {
                this["MaxWorkingMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MinBreakingMinutes {
            get {
                return ((int)(this["MinBreakingMinutes"]));
            }
            set {
                this["MinBreakingMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MaxDelayMinutes {
            get {
                return ((int)(this["MaxDelayMinutes"]));
            }
            set {
                this["MaxDelayMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal MinBreakingPercent {
            get {
                return ((decimal)(this["MinBreakingPercent"]));
            }
            set {
                this["MinBreakingPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F12")]
        public global::System.Windows.Forms.Keys ShutdownMonitorHotkey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ShutdownMonitorHotkey"]));
            }
            set {
                this["ShutdownMonitorHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Resctrition4RestartWorking {
            get {
                return ((int)(this["Resctrition4RestartWorking"]));
            }
            set {
                this["Resctrition4RestartWorking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hand")]
        public string SystemSound4CompletingBreak {
            get {
                return ((string)(this["SystemSound4CompletingBreak"]));
            }
            set {
                this["SystemSound4CompletingBreak"] = value;
            }
        }
    }
}
